apiVersion: v1
kind: Pod
metadata:
  name: hello-world-cic
  labels:
    app: hello-world-cic
spec: 
      serviceAccountName: cpx
      containers:
      - name: hello-world-cic
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.1.3"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "10.217.101.176"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "NO"
         - name: "NS_USER"
           value: "nsroot"
         - name: "NS_PASSWORD"
           value: "nsroot"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "DEBUG"
         - name: "NS_VIP"
           value: "10.217.101.183"
         - name: "NS_APPS_NAME_PREFIX"
           value: "HW-"
        args:
          - --ingress-classes
            helloworld-unified
          - --feature-node-watch
            false
        imagePullPolicy: IfNotPresent