apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: LoadBalancer
  loadBalancerIP: ""
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: load-balancer-example
